config/routes.rb
Rails.application.routes.draw do
  get "download_pdf/:warehouse_id", to: "items#download_pdf", as: "download_pdf"
  get "preview_pdf/:warehouse_id", to: "items#preview_pdf", as: "preview_pdf"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  resources :users_admin, controller: 'users' do
    collection do
      post '/search_users', to: 'users#search_users', as: :search_users
    end
    resources :access_alloweds, only: %i[create new destroy] do
      collection do
        post '/search_warehouse', to: 'access_alloweds#search_warehouse', as: :search_warehouse
      end
    end
  end
  resources :pos_sessions do
    get '/transaktions/:id/annullated', to: 'transaktions#annullated', as: 'transaktion_annullated'
    get '/transaktions/:id/paying', to: 'transaktions#paying', as: 'transaktion_paying'
    resources :transaktions, only: %i[index create edit update destroy show] do
      collection do
        delete '/delete/:id', to: 'search_transaktions#delete_session', as: :delete
        delete '/delete_all', to: 'search_transaktions#delete_all_session', as: :delete_all
        post '/search', to: 'search_transaktions#search_product_purchase', as: :search
        post '/search_transaktions', to: 'search_transaktions#search_transaktions', as: :search_transaktions
        post '/search_sale', to: 'search_transaktions#search_product_sale', as: :search_sale
        post '/search_market', to: 'search_transaktions#search_market_rates', as: :search_market
        post '/search_provider', to: 'search_transaktions#search_provider', as: :search_provider
        post '/search_warehouse', to: 'search_transaktions#search_warehouse', as: :search_warehouse
        post '/create_sale', to: 'search_transaktions#create_sales_with_customer', as: :create_sale
        post '/create_transfer', to: 'search_transaktions#create_item_transfer', as: :create_transfer
        post '/item_transactions', to: 'search_transaktions#item_transactions_session', as: :item_transactions
      end
    end

    collection do
      post '/search_pos_sessions', to: 'pos_sessions#search_pos_sessions', as: :search_pos_sessions
    end

    get '/sales', to: 'transaktions#sales'
    get '/purchases', to: 'transaktions#purchases'
    get '/market_rates', to: 'transaktions#market_rates'
    get '/item_transfer', to: 'transaktions#item_transfer'
    get '/modal_create_product', to: 'search_transaktions#modal_create_product'
    get '/modal_confirm_market_rates', to: 'search_transaktions#modal_confirm_market_rates'
    get '/modal_confirm_transfer', to: 'search_transaktions#modal_confirm_transfer'
  end

  get '/payment_center', to: 'transaktions#payment_center'

  resources :providers do
    collection do
      get '/modal_new', to: 'providers#modal_new'
      post '/searches', to: 'providers#searches'
      post '/search', to: 'providers#search'
    end
  end

  resources :buyers do
    collection do
      post '/searches', to: 'buyers#searches'
      post '/search', to: 'buyers#search'
    end
  end

  resources :orders, only: :index

  resources :products do
    collection do
      post '/search_products', to: 'products#search_products', as: :search_products
      post '/search_providers', to: 'products#search_providers', as: :search_providers
    end
  end
  resources :accounts, only: %i[create show edit update destroy]
  resources :warehouses do
    collection do
      post '/search_warehouses', to: 'warehouses#search_warehouses', as: :search_warehouses
    end
    resources :warehouse_details, only: %i[create update]
    resources :items do
      collection do
        post '/search_product', to: 'items#search_product', as: :search_product
        post '/search_items', to: 'items#search_items', as: :search_items
      end
    end
  end
end

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
# Defines the root path route ("/")

app/controllers/transaktions_controller.rb
class TransaktionsController < ApplicationController
  before_action :set_pos_session, except: %i[payment_center]
  before_action :set_payment_methods, only: %i[create sales update market_rates purchases paying]
  before_action :set_transaktion, only: %i[show edit update paying annullated]
  before_action :set_breadcrumbs_transaktions, only: %i[
    index show edit sales market_rates purchases item_transfer
  ]
  before_action :set_payment_breadcrumbs, only: %i[payment_center]

  def index
    @filter_transaktions = set_filter_transaktions
    if params[:type_filter].present?
      @transaktions = policy_scope(Transaktion).where(
        pos_session_id: params[:pos_session_id], type_transaktion: params[:type_filter]
      ).page(params[:page]).per(15).order(id: :desc)
    else
      @transaktions = policy_scope(Transaktion).where(
        pos_session_id: params[:pos_session_id]
      ).page(params[:page]).per(15).order(id: :desc)
    end
    authorize @transaktions
  end

  def create
    @transaktion = Transaktion.new(transaction_params)
    @transaktion.pos_session_id = @pos_session.id

    create_purchases(@transaktion)
  end

  def show
    @item_transactions = @transaktion.item_transactions.page(params[:page]).per(15).order(id: :desc)
    if @transaktion.annulled?
      @badge_type = 'danger'
    elsif @transaktion.active?
      @badge_type = 'success'
    else
      @badge_type = 'secondary'
    end
  end

  def edit; end

  def sales
    session[:item_transactions_sales] ||= []
    @sale = Transaktion.new
    @sale.build_customer
  end

  def market_rates
    session[:item_transactions_market_rates] ||= []
    @market_rate = Transaktion.new
    @market_rate.build_customer
  end

  def purchases
    session[:item_transactions_purchase] ||= []
    @purchase = Transaktion.new
  end

  def item_transfer
    session[:item_transactions_transfer] ||= []
  end

  def annullated
    @pos_sessions_active = PosSession.where(
      warehouse_id: @pos_session.warehouse_id, status: 'active'
    )
  end

  def paying
    @open_sessions = @pos_session&.warehouse&.pos_sessions&.active
  end

  def payment_center
    @pending_payments = Transaktion.where(
      type_transaktion: 'Purchases Credit', status: 'pending'
    ).page(params[:page]).per(20).order(id: :desc)
    @completed_payments = Transaktion.where(
      type_transaktion: 'Purchases Credit', status: 'active'
    ).page(params[:page]).per(20).order(id: :desc)
    authorize @pending_payments
  end

  def update
    @pending_payments = Transaktion.where(
      type_transaktion: 'Purchases Credit', status: 'pending'
    )
    case @transaktion.type_transaktion
    when 'Market rates' then update_market_rates(@transaktion)
    when 'Transfer' then update_transfer(@transaktion)
    when 'Purchases Credit' then update_purchase_credit(@transaktion, @payment_methods)
    end
    annullated_transaktion(@pos_session, @transaktion)
  end

  private

  def transaction_params
    params.require(:transaktion).permit(
      :id, :pos_session_id, :customer_id, :type_transaktion, :total, :status, :description,
      :money_received, :money_returned, :money_paid, :payment_method, :code, :discount,
      :date_of_payment, :receiver_pos_session_id, :destination_warehouse_id, :customer_received_money_id,
      :receipt_number, :invoice_number
    )
  end

  def transaktion_type_params
    params.require(:transaktion).permit(
      :id, :customer_id, :type_transaktion, :total, :status,
      :description, :money_received, :money_returned, :money_paid, :payment_method,
      :code, :discount, :receiver_pos_session_id, :destination_warehouse_id, :customer_received_money_id,
      :receipt_number, :invoice_number
    )
  end

  def set_pos_session
    @pos_session = PosSession.find(params[:pos_session_id])
    authorize @pos_session
  end

  def set_transaktion
    @transaktion = Transaktion.find(params[:id])
    authorize @transaktion
  end

  def set_breadcrumbs_transaktions
    add_breadcrumb 'Cajas', :pos_sessions_path
    add_breadcrumb @pos_session.warehouse.name, pos_session_path(@pos_session)
    add_breadcrumb 'Movimientos', pos_session_transaktions_path(@pos_session) if action_name == 'index' || @transaktion
    add_breadcrumb @transaktion.id, pos_session_transaktion_path(@pos_session, @transaktion) if @transaktion
    add_breadcrumb 'Compra', pos_session_purchases_path(@pos_session) if action_name == 'purchases'
    add_breadcrumb 'Venta', pos_session_sales_path(@pos_session) if action_name == 'sales'
    add_breadcrumb 'Cotización', pos_session_market_rates_path(@pos_session) if action_name == 'market_rates'
    add_breadcrumb 'Traspaso', pos_session_item_transfer_path(@pos_session) if action_name == 'item_transfer'
  end

  def set_payment_breadcrumbs
    add_breadcrumb 'Pagos', payment_center_path
  end

  def create_purchases(purchase)
    item = Item.find(session[:item_transactions_purchase][0]['item_id'])
    purchase.customer_id = item.product.customer_id
    notice_message = "#{purchase.type_transaktion_es} realizada con exito!"

    if purchase.type_transaktion == 'Purchases' && !purchase.customer_received_money_id
      collector = Customer.create(
        name: params[:name_collector], document_number: params[:ci_collector], account_id: current_account.id, type: "Collector"
      )
      purchase.customer_received_money_id = collector.id
    end

    if purchase.save
      session[:item_transactions_purchase].each do |obj|
        ItemTransaction.create(
          item_id: obj['item_id'], transaktion_id: purchase.id,
          qty: obj['unit_total'], sub_total: obj['sub_total']
        )
      end
      session[:item_transactions_purchase] = []
      redirect_to pos_session_path(@pos_session), notice: notice_message
    else
      render 'transaktions/purchases', status: :unprocessable_entity
    end
  end

  def update_market_rates(transaktion)
    transaktion.status = 'active'
    notice_message = 'Cotización confirmada con exito!'
    if transaktion.update(transaktion_type_params)
      redirect_to pos_session_path(@pos_session), notice: notice_message
    else
      render turbo_stream: turbo_stream.update(
        'confirm_market_rates',
        partial: 'shared/forms/form_confirm_market_rates',
        locals: { pos_session: @pos_session }
      )
    end
  end

  def update_transfer(transaktion)
    if transaktion.destination_warehouse_id == @pos_session.warehouse_id && transaktion.status == 'sent'
      transaktion.status = 'active'
      notice_message = 'Transpaso de Productos confirmado con exito!'
      if transaktion.update(transaktion_type_params)
        redirect_to pos_session_path(@pos_session), notice: notice_message
      else
        render turbo_stream: turbo_stream.update(
          'confirm_transfer',
          partial: 'shared/forms/form_confirm_transfer',
          locals: { pos_session: @pos_session }
        )
      end
    end
  end

  def update_purchase_credit(transaktion, payment_methods)
    comparison = transaktion_type_params[:receiver_pos_session_id].present? && transaktion.status == 'pending'
    if comparison && transaktion.pos_session.warehouse_id == @pos_session.warehouse_id
      notice_message = 'Compra al credito pagada con exito!'
      transaktion.active!
      if transaktion.update(transaktion_type_params)
        redirect_to pos_session_path(@pos_session), notice: notice_message
      else
        render turbo_stream: turbo_stream.update(
          'paying_transaktion',
          partial: 'shared/forms/form_paying_transaktion',
          locals: { pos_session: @pos_session, transaktion: transaktion,
            payment_methods: payment_methods
          }
        )
      end
    end
  end

  def set_filter_transaktions
    [
      ['Compra al Credito', 'Purchases Credit'], %w[Compra Purchases],
      %w[Venta Sales], %w[Traspaso Transfer], ['Cotización', 'Market rates']
    ]
  end

  def set_payment_methods
    @payment_methods = ['Efectivo', 'Pago QR', 'Tarjeta', 'Transferencia']
  end

  def annullated_transaktion(pos_session, transaktion)
    if params[:annullated] == 'true' && transaktion_type_params[:receiver_pos_session_id].present?
      transaktion.status = 'annulled'
      notice_message = "#{transaktion.type_transaktion_es}, Anulado con Exito!"
      if transaktion.update(transaktion_type_params)
        annulled_inventory(transaktion)
        redirect_to pos_session_transaktion_path(pos_session, transaktion), notice: notice_message
      else
        render turbo_stream: turbo_stream.update(
          'annullated_transaktion',
          partial: 'shared/forms/form_annullated_transaktion',
          locals: { pos_session: pos_session, transaktion: transaktion }
        )
      end
    end
  end

  def annulled_inventory(transaktion)
    if transaktion.type_transaktion == 'Sales' || (transaktion.type_transaktion == 'Market rates' && transaktion.status == 'active')
      transaktion.item_transactions.each do |obj|
        item = Item.find(obj.item_id)
        item.total_stock += obj.qty
        item.quantity += obj.qty / item.product.total_unit
        item.save
        obj.update(stock_at: item.total_stock)
      end
    elsif transaktion.type_transaktion == 'Transfer'
      transaktion.item_transactions.each do |obj|
        item_emitter = Item.find(obj.item_id)
        item_emitter.total_stock += obj.qty
        item_emitter.quantity += obj.qty / item_emitter.product.total_unit
        item_emitter.save
        obj.update(stock_at: item_emitter.total_stock)
        item_receiver = Item.find_by(
          warehouse_id: transaktion.destination_warehouse_id, product_id: item_emitter.product.id
        )
        item_receiver.total_stock -= obj.qty
        item_receiver.quantity -= obj.qty / item_receiver.product.total_unit
        item_receiver.save
      end
    else
      transaktion.item_transactions.each do |obj|
        item = Item.find(obj.item_id)
        item.total_stock -= obj.qty

app/helpers/transaktions_helper.rb
module TransaktionsHelper
end

app/views/transaktions/annullated.html.erb
<%= turbo_frame_tag "modal_annullated_transaktion" do %>
  <section id="myModal2" class="modal2">
    <div class="modal-content2">
      <h2>Anular <%= @transaktion.type_transaktion_es %></h2>
      <div class="my-4">
        <%=
          render partial: "shared/forms/form_annullated_transaktion",
            locals: {
              transaktion: @transaktion, pos_session: @pos_session,
              pos_sessions_active: @pos_sessions_active
            }
        %>
      </div>
    </div>
  </section>
<% end %>

app/views/transaktions/edit.html.erb
<section>
</section>

app/views/transaktions/index.html.erb
<section class="app-papper row justify-content-between" data-controller="transaktions">
  <div class="col-12">
    <h5 class="mb-4">
      <%= @pos_session.user.full_name %>
      (<%= @pos_session.user.role.name_es || @pos_session.user.role.name %>)
      <%= @pos_session.created_at.localtime.strftime("%d-%m-%Y") %>
    </h5>
  </div>
  <div class="col-6 mb-4">
    <%= form_with url: search_transaktions_pos_session_transaktions_path(@pos_session),
        method: :post, class: "purchase-search-products-form",
        data: { transaktions_target: "formSearchTransaktions" } do |form|
    %>
      <%= form.hidden_field :pos_session_context, value: @pos_session.id,
          data: { transaktions_target: "posSessionContextTransaktion" } %>
      <%= form.label "Buscar Transacción" %>
      <%=
        form.search_field :search_transaktions, id: "search-input",
          class: "form-control purchase-search-input",
          data: {
            action: "input->transaktions#searchTransaktions",
            transaktions_target: "inputSearchTransaktions"
          }
      %>
    <% end %>
  </div>
  <div class="col-6 col-md-4 col-lg-3">
    <%= form_with url: pos_session_transaktions_path(@pos_session),
        method: :get, class: "purchase-search-products-form",
        data: { transaktions_target: "formSearchTransaktionsFilter" } do |form|
    %>
      <%= form.label "Filtrar por:" %>
      <%=
        form.select :type_filter,  options_for_select(@filter_transaktions, params[:type_filter]),
          { include_blank: 'Seleccionar' },
          class: "form-control purchase-search-input",
          data: { action: "change->transaktions#sendRequestTransaktionFilter" }
      %>
    <% end %>
  </div>
  <div id="transaktions_movements_search" class="table-responsive col-12">
    <%= render partial: 'shared/tables/table_transaktion',
      locals: { transaktions: @transaktions } %>
    <%= render partial: 'shared/pagination', locals: { records_pagination: @transaktions } %>
  </div>
</section>

app/views/transaktions/paying.html.erb
<%= turbo_frame_tag "modal_paying_transaktion" do %>
  <section id="myModal2" class="modal2">
    <div class="modal-content2">
      <h2>Pagar <%= @transaktion.type_transaktion_es %></h2>
      <div class="my-4">
        <%= render partial: "shared/forms/form_paying_transaktion",
            locals: {
              transaktion: @transaktion,
              pos_session: @pos_session,
              open_sessions: @open_sessions,
              payment_methods: @payment_methods
            }
        %>
      </div>
    </div>
  </section>
<% end %>

app/views/transaktions/payment_center.html.erb
<section class="app-papper my-2">
  <h5><%= t('payment.pending.title') %></h5>
  <%= render partial: 'shared/tables/table_payments', locals: { payments: @pending_payments } %>
  <%= render partial: 'shared/pagination', locals: { records_pagination: @pending_payments } %>

  <h5><%= t('payment.completed.title') %></h5>
  <%= render partial: 'shared/tables/table_payments', locals: { payments: @completed_payments } %>
  <%= render partial: 'shared/pagination', locals: { records_pagination: @completed_payments } %>
</section>

app/views/transaktions/purchases.html.erb
<section class="purchases-container" data-controller="purchase">
  <div class="app-papper justify-content-center mb-3">
    <div class="purchase-search-products row justify-content-between">
      <div class="col-12">
          <h5 class="">
            Proveedor
          </h5>
        <%= form_with url: providers_path, method: :post,
              class: "purchase-search-products-form",
              data: { purchase_target: "formSearchProvider" } do |form|
        %>
          <%= form.hidden_field :pos_session_id, value: @pos_session.id,
                data: { purchase_target: "posSessionIdPurchase" } %>
          <div class="row justify-content-between">
            
            <div class="col-6 col-md-4">
              <%= form.label "NIT/CI" %>
              <%=
                form.number_field :document_number, id: "search-input",
                  class: "form-control purchase-search-input",
                  data: {
                    action: "input->purchase#searchProvider",
                    purchase_target: "inputSearchProvider"
                  }
              %>
            </div>
            
            <div class="col-6 col-md-4">
              <%= form.label "Razón Social" %>
              <%=
                form.text_field :name, id: "search-input",
                  class: "form-control purchase-search-input",
                  data: { purchase_target: "socialReasonPurchaseProvider" }
              %>
            </div>

            <div class="col-6 col-md-4">
              <%= form.label "Correo eletrónico" %>
              <%=
                form.text_field :email, id: "search-input",
                  class: "form-control purchase-search-input",
                  data: { purchase_target: "emailPurchaseProvider" }
              %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-6 col-md-4 col-lg-3">
        <%=
          link_to "Crear Proveedor", modal_new_providers_path,
            class: "btn btn-outline-primary purchases-button-create-product",
            data: { turbo_frame: "modal_new_provider" }
        %>
      </div>
    </div>
  </div>
  <div class="app-papper justify-content-center">
    <div class="purchase-search-products row justify-content-between">
      <div class="col-12 col-md-4">
        <%=
          form_with url: search_pos_session_transaktions_path(@pos_session),
          method: :post, class: "purchase-search-products-form",
          data: { purchase_target: "formSearch" } do |form|
        %>
          <%= form.hidden_field :customer_id, data: { purchase_target: "providerId" } %>
          <%= form.label "Buscar producto del proveedor:" %>
          <span data-purchase-target="providerName"></span>
          <%=
            form.search_field :search, id: "search-input",
              class: "form-control purchase-search-input",
              data: {
                action: "input->purchase#searchProduct",
                purchase_target: "inputSearchProduct"
              }
          %>
        <% end %>
      </div>
      <div class="col-6 col-md-4 col-lg-3">
        <%= link_to "Crear Producto", pos_session_modal_create_product_path(@pos_session),
            class: "btn btn-outline-primary purchases-button-create-product",
            data: { turbo_frame: "modal_create_product" } %>
      </div>
      <div
        data-purchase-target="searchResults"
        class="col-12 search_results"
        id="search_results_purchase"
      ></div>
    </div>
    <div class="table-responsive my-4">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col" class="min-width-6">Descripción</th>
            <th scope="col">Unidades Caja</th>
            <th scope="col">Costo Unitario</th>
            <th scope="col">Costo Caja</th>
            <th scope="col">Stock Min.</th>
            <th scope="col">Stock Max.</th>
            <th scope="col">Total Stock</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td data-purchase-target="productDescription" class="min-width-6" scope="row"></td>
            <td data-purchase-target="unitPackage"></td>
            <td data-purchase-target="costUnit"></td>
            <td data-purchase-target="costPackage"></td>
            <td data-purchase-target="minStock"></td>
            <td data-purchase-target="maxStock"></td>
            <td data-purchase-target="totalStock"></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="purchase-item-transactions-form mt-4">
      <%= form_with url: item_transactions_pos_session_transaktions_path(@pos_session),
          data: { purchase_target: "formPurchaseItemTransaktionAdd" },
          method: :post do |form| %>
        <input type="hidden" data-purchase-target="subtotalProduct">
        <input type="hidden" data-purchase-target="qtyPerPackage">
        <%= form.hidden_field :purchase, value: 'true' %>
        <%= form.hidden_field :product_id, data: { purchase_target: "productId" } %>
        <%= form.hidden_field :qty_unit, data: { purchase_target: "qtyUnitPurchase" } %>
        <%= form.hidden_field :item_id, data: { purchase_target: "itemId" } %>
        <div class="row">
          <div class="col-6 col-lg-3">
            <%= form.label "Unidades" %>
            <%=
              form.number_field :unit_total,
                class: "form-control purchase-item-transactions-input",
                data: {
                  action: "input->purchase#sumSubtotalForUnits",
                  purchase_target: "unitTotalPurchase"
                }
            %>
          </div>
          <div class="col-6 col-lg-4 col-xl-3">
            <%= form.label "Cantidad Paq./Caja" %>
            <%=
              form.number_field :qty_package,
                class: "form-control purchase-item-transactions-input",
                data: {
                  action: "input->purchase#sumSubtotalForPackage",
                  purchase_target: "qtyPackagePurchase"
                }
            %>
          </div>
          <div class="col-6 col-lg-3">
            <%= form.label :subtotal %>
            <%= form.hidden_field :sub_total, step: '0.01',
                class: "form-control", data: { purchase_target: "subtotal" } %>
            <div>
              <p class="fw-bold h5 mt-2 d-inline-block" data-purchase-target="subtotalSee">
                0
              </p>
              <p class="fw-bold h5 mt-2 d-inline-block">
                <%= @pos_session.type_of_currency %>
              </p>
            </div>
          </div>
          <div class="col-6 col-lg-2">
            <button
              type="button" data-action="click->purchase#addItemTransaktionAndReset"
              class="btn btn-outline-primary sale-align-button-item-transaktions-add"
            >
              Agregar
            </button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="app-papper my-3" id="item_transactions_purchase">
    <%= render partial: "shared/tables/table_items_added_purchases",
        locals: { item_transactions: session[:item_transactions_purchase] } %>
  </div>
  <div class="app-papper my-3">
    <div class="mb-4">
      <div class="d-inline-block">
        <input
          type="checkbox" class="form-check-input my-2" value="Purchases"
          data-purchase-target="checkboxPurchases" checked
          data-action="change->purchase#setTypePurchasesSelected"
        >
        <label for="checkbox" class="form-check-label my-1">
          Compra al Contado
        </label>
      </div>
      <div class="d-inline-block mx-4">
        <input
          type="checkbox" class="form-check-input my-2"
          data-purchase-target="checkboxPurchasesCredit" value="Purchases Credit"
          data-action="change->purchase#setTypePurchasesCreditSelected"
        >
        <label for="checkbox" class="form-check-label my-1">
          Compra al Credito
        </label>
      </div>
    </div>
    <%= bootstrap_form_for([@pos_session, @purchase]) do |f| %>
      <%= f.hidden_field :type_transaktion, value: "Purchases",
          data: { purchase_target: "typeTransaktionPurchase" } %>
      <%= f.hidden_field :customer_received_money_id,
            data: { purchase_target: "customerReceivedMoneyId" } %>
      <%= f.hidden_field :total, data: { purchase_target: "totalPurchase" } %>
      <%= f.hidden_field :status, value: "active", data: { purchase_target: "statusPurchase" } %>
      <div class="row justify-content-start">
        <div class="col-6 col-md-4">
          <%= f.text_area :description, rows: 1,
                label: t('forms.models.transaktion.labels.description') %>
        </div>
        <div class="col-6 col-md-4 d-none" id="purchases-credit-date">
          <%= f.date_field :date_of_payment,
                data: { purchase_target: "dateOfPaymentPurchase" },
                label: t('forms.models.transaktion.labels.date_of_payment') %>
        </div>
        <div class="col-6 col-md-4">
          <%= f.number_field :invoice_number,
                label: t('forms.models.transaktion.labels.invoice_number') %>
        </div>
        <div class="col-6 col-md-4">
          <%= f.text_field :receipt_number,
                label: t('forms.models.transaktion.labels.receipt_number') %>
        </div>
        <div class="col-6 col-md-4 purchases-selector-hidden-toggle">
          <%=
            f.number_field :money_paid, step: '0.01',
              label: t('forms.models.transaktion.labels.money_paid'),
              data: {
                purchase_target: "moneyPaidPurchases",
                action: "input->purchase#setMoneyReceived"
              }
          %>
        </div>
        <div class="col-6 col-md-4 purchases-selector-hidden-toggle">
          <%= f.label t('forms.models.transaktion.labels.money_received') %>
          <%= f.hidden_field :money_received, step: '0.01',
              data: { purchase_target: "moneyReceivedPurchase" } %>
          <div>
            <p class="fw-bold h5 mt-3 d-inline-block" data-purchase-target="moneyReceivedPurchaseSee">
              0
            </p>
            <p class="fw-bold h5 mt-3 d-inline-block">
              <%= @pos_session.type_of_currency %>
            </p>
          </div>
        </div>
        <div class="col-6 col-md-4 purchases-selector-hidden-toggle">
          <%= f.select :payment_method,
                options_for_select(@payment_methods, 'Efectivo'),
                class: "form-control",
                label: t('forms.models.transaktion.labels.payment_method') %>
        </div>
        <div class="col-12 my-3 purchases-selector-hidden-toggle">
          <h5 class="fw-bold">Datos del Cobrador</h5>
        </div>
        <div class="col-4 purchases-selector-hidden-toggle">
          <label class="my-2">CI</label>
          <input
            data-action="input->purchase#searchCollector"
            data-purchase-target="customerReceivedCi"
            class="form-control" type="text" name="ci_collector"
          >
        </div>
        <div class="col-4 purchases-selector-hidden-toggle">
          <label class="my-2">Nombre</label>
          <input
            data-purchase-target="customerReceivedName"
            class="form-control" type="text" name="name_collector"
          >
        </div>
        <div class="col-6 col-md-4 purchase-align-button-transaktion-new">
          <%= f.submit "Realizar Compra", class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
  </div>
</section>