config/routes.rb
Rails.application.routes.draw do
  get "download_pdf/:warehouse_id", to: "items#download_pdf", as: "download_pdf"
  get "preview_pdf/:warehouse_id", to: "items#preview_pdf", as: "preview_pdf"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  resources :users_admin, controller: 'users' do
    collection do
      post '/search_users', to: 'users#search_users', as: :search_users
    end
    resources :access_alloweds, only: %i[create new destroy] do
      collection do
        post '/search_warehouse', to: 'access_alloweds#search_warehouse', as: :search_warehouse
      end
    end
  end
  resources :pos_sessions do
    get '/transaktions/:id/annullated', to: 'transaktions#annullated', as: 'transaktion_annullated'
    get '/transaktions/:id/paying', to: 'transaktions#paying', as: 'transaktion_paying'
    resources :transaktions, only: %i[index create edit update destroy show] do
      collection do
        delete '/delete/:id', to: 'search_transaktions#delete_session', as: :delete
        delete '/delete_all', to: 'search_transaktions#delete_all_session', as: :delete_all
        post '/search', to: 'search_transaktions#search_product_purchase', as: :search
        post '/search_transaktions', to: 'search_transaktions#search_transaktions', as: :search_transaktions
        post '/search_sale', to: 'search_transaktions#search_product_sale', as: :search_sale
        post '/search_market', to: 'search_transaktions#search_market_rates', as: :search_market
        post '/search_provider', to: 'search_transaktions#search_provider', as: :search_provider
        post '/search_warehouse', to: 'search_transaktions#search_warehouse', as: :search_warehouse
        post '/create_sale', to: 'search_transaktions#create_sales_with_customer', as: :create_sale
        post '/create_transfer', to: 'search_transaktions#create_item_transfer', as: :create_transfer
        post '/item_transactions', to: 'search_transaktions#item_transactions_session', as: :item_transactions
      end
    end

    collection do
      post '/search_pos_sessions', to: 'pos_sessions#search_pos_sessions', as: :search_pos_sessions
    end

    get '/sales', to: 'transaktions#sales'
    get '/purchases', to: 'transaktions#purchases'
    get '/market_rates', to: 'transaktions#market_rates'
    get '/item_transfer', to: 'transaktions#item_transfer'
    get '/modal_create_product', to: 'search_transaktions#modal_create_product'
    get '/modal_confirm_market_rates', to: 'search_transaktions#modal_confirm_market_rates'
    get '/modal_confirm_transfer', to: 'search_transaktions#modal_confirm_transfer'
  end

  get '/payment_center', to: 'transaktions#payment_center'

  resources :providers do
    collection do
      get '/modal_new', to: 'providers#modal_new'
      post '/searches', to: 'providers#searches'
      post '/search', to: 'providers#search'
    end
  end

  resources :buyers do
    collection do
      post '/searches', to: 'buyers#searches'
      post '/search', to: 'buyers#search'
    end
  end

  resources :orders, only: :index

  resources :products do
    collection do
      post '/search_products', to: 'products#search_products', as: :search_products
      post '/search_providers', to: 'products#search_providers', as: :search_providers
    end
  end
  resources :accounts, only: %i[create show edit update destroy]
  resources :warehouses do
    collection do
      post '/search_warehouses', to: 'warehouses#search_warehouses', as: :search_warehouses
    end
    resources :warehouse_details, only: %i[create update]
    resources :items do
      collection do
        post '/search_product', to: 'items#search_product', as: :search_product
        post '/search_items', to: 'items#search_items', as: :search_items
      end
    end
  end
end

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
# Defines the root path route ("/")

app/views/shared/tables/_table_customers.html.erb
<div class="table-responsive">
  <table class="table table-striped table-hover table-warehouse-items table-bordered">
    <thead>
      <tr>
        <th scope="col" class="text-center">ID</th>
        <th scope="col" class="min-width-2">NIT/CI</th>
        <th scope="col" class="min-width-4"><%= kind == 'buyer' ? 'Nombre' : 'Razón Social' %></th>
        <th scope="col" class="min-width-2">Correo</th>
        <th scope="col" class="min-width-2">Telefono</th>
        <th scope="col" class="min-width-1">Estado</th>
      </tr>
    </thead>
    <tbody>
      <% customers.each do |obj| %>
        <% redirect_id = send("#{obj.type.downcase}_path", obj) %>
        <tr id="<%= redirect_id %>" class="cursor-pointer" data-action="click->customers#redirectShowCustomer">
          <th id="<%= redirect_id %>" scope="row"><%= obj.id %></th>
          <td id="<%= redirect_id %>" class="min-width-2"><%= obj.document_number%></td>
          <td id="<%= redirect_id %>" class="min-width-3"><%= obj.name %></td>
          <td id="<%= redirect_id %>" class="min-width-2"><%= obj.email %></td>
          <td id="<%= redirect_id %>" class="min-width-2"><%= obj.phone %></td>
          <td id="<%= redirect_id %>" class="min-width-1"><%= obj.status_es %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/tables/_table_item.html.erb
<div class="table-responsive">
    <table class="table table-striped table-hover table-warehouse-items">
      <caption>Total Items: <%= items.count %></caption>
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Código</th>
          <th scope="col" class="min-width-2">Nombre</th>
          <th scope="col" class="min-width-4">Descripción</th>
          <th scope="col">Costo lista</th>
          <th scope="col">Costo Unidad</th>
          <th scope="col">Costo Paq./Caja</th>
          <th scope="col">P.Venta Paq./Caja</th>
          <th scope="col">P.Venta Unidad</th>
          <th scope="col">Total Stock</th>
          <th scope="col">Total Paq./Caja</th>
          <th scope="col">Min. Stock</th>
          <th scope="col">Max. Stock</th>
          <th scope="col">Nombre Genérico</th>
        </tr>
      </thead>
      <tbody>
        <% items.each do |obj| %>
          <% redirect_id = warehouse_item_path(@warehouse, obj) %>
          <tr
            id="<%= redirect_id %>" class="cursor-pointer"
            data-action="click->item#redirectItemShow"
          >
            <th id="<%= redirect_id %>" scope="row"><%= obj.id %></th>
            <td id="<%= redirect_id %>"><%= obj.product&.code || obj.product&.import_id || obj.product&.alternative_code %></td>
            <td id="<%= redirect_id %>" class="min-width-2"><%= obj.product&.name %></td>
            <td id="<%= redirect_id %>" class="min-width-4"><%= obj.product&.description %></td>
            <td id="<%= redirect_id %>"><%= obj.list_price %></td>
            <td id="<%= redirect_id %>"><%= obj.purchase_cost_unit %></td>
            <td id="<%= redirect_id %>"><%= obj.purchase_cost_package %></td>
            <td id="<%= redirect_id %>"><%= obj.sale_price_package %></td>
            <td id="<%= redirect_id %>"><%= obj.sale_price_unit %></td>
            <td id="<%= redirect_id %>"><%= obj.total_stock %></td>
            <td id="<%= redirect_id %>"><%= obj.quantity %></td>
            <td id="<%= redirect_id %>"><%= obj.min_stock %></td>
            <td id="<%= redirect_id %>"><%= obj.max_stock %></td>
            <td id="<%= redirect_id %>"><%= obj.product&.generic_name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/shared/tables/_table_item_transaction.html.erb
<div class="table-responsive">
  <table class="table table-striped table-hover table-warehouse-items">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col" class="min-width-2">Producto</th>
        <th scope="col" class="min-width-6">Descripción</th>
        <th scope="col" class="min-width-1">C. Unidad</th>
        <th scope="col" class="min-width-1">C. Paq/Caja</th>
        <th scope="col" class="min-width-1">Subtotal</th>
      </tr>
    </thead>
    <tbody>
      <% item_transactions.each do |obj| %>
        <tr>
          <th scope="row"><%= obj.id %></th>
          <td class="min-width-2"><%= obj.item.product.name %></td>
          <td class="min-width-4"><%= obj.item.product.description %></td>
          <td class="min-width-1"><%= obj.qty %></td>
          <td class="min-width-1"><%= obj.qty / obj.item.product.total_unit%></td>
          <td class="min-width-1">
            <%= obj.sub_total %> <%= obj.transaktion.pos_session.type_of_currency %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/tables/_table_items_added_market_rates.html.erb
<div class="table-responsive">
  <table class="table table-striped table-hover table-warehouse-items">
    <caption>Total registros: <%= item_transactions.count %></caption>
    <thead>
      <tr>
        <th scope="col">Código</th>
        <th scope="col" class="min-width-4">Descripción</th>
        <th scope="col">Unidades</th>
        <th scope="col">Cajas</th>
        <th scope="col">Precio</th>
        <th scope="col">Precio Caja</th>
        <th scope="col">Total Unidades</th>
        <th scope="col">Subtotal</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% total_mount = 0 %>
      <% item_transactions.each do |obj| %>
        <% item = Item.find(obj["item_id"]) %>
        <% total_mount += obj["sub_total"].to_f %>
        <tr>
          <td><%= item.code %></td>
          <td class="min-width-4" data-market-target="itemDescription">
            <%= item.product.description %>
          </td>
          <td><%= obj["qty_unit"] %></td>
          <td><%= obj["qty_package"] %></td>
          <td><%= item.sale_price_unit %></td>
          <td><%= item.sale_price_package %></td>
          <td><%= obj["unit_total"] %></td>
          <td><%= obj["sub_total"] %></td>
          <td>
            <%= link_to "/pos_sessions/#{@pos_session.id}/transaktions/delete/#{obj["item_id"]}?market_rates=true",
              data: { turbo_method: :delete, turbo_confirm: "Estas seguro de eliminar?" } do %>
              <i class="fa fa-trash" color="black" aria-hidden="true"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td scope="row" colspan="6">
          <%=
            link_to "Borrar Todo", "/pos_sessions/#{@pos_session.id}/transaktions/delete_all?market_rates=true",
              class: "text-decoration-none",
              data: {
                turbo_method: :delete,
                turbo_confirm: "Estas seguro de eliminar todo?"
              }
          %>
        </td>
        <th colspan="3">
          <span class="mx-2">
            Total:
          </span>
          <span class="h5 fw-bold" data-market-target="sumTotalItemTransactions">
            <%= total_mount.round(2) %>
          </span>
          <span class="h5 fw-bold">
            <%= @pos_session.type_of_currency %>
          </span>
        </th>
      </tr>
    </tbody>
  </table>
</div>

app/views/shared/tables/_table_items_added_purchases.html.erb
<div class="table-responsive">
  <table class="table table-striped table-hover table-warehouse-items">
    <caption>Total registros: <%= item_transactions.count %></caption>
    <thead>
      <tr>
        <th scope="col">Código</th>
        <th scope="col" class="min-width-4">Descripción</th>
        <th scope="col">Unidades</th>
        <th scope="col">Cajas</th>
        <th scope="col">Costo</th>
        <th scope="col">Costo Caja</th>
        <th scope="col">Total Unidades</th>
        <th scope="col">Subtotal</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% total_mount = 0 %>
      <% item_transactions.each do |obj| %>
        <% item = Item.find(obj["item_id"]) %>
        <% total_mount += obj["sub_total"].to_f %>
        <tr>
          <td><%= item.code %></td>
          <td class="min-width-4"><%= item.product.description %></td>
          <td><%= obj["qty_unit"] %></td>
          <td><%= obj["qty_package"] %></td>
          <td><%= item.purchase_cost_unit %></td>
          <td><%= item.purchase_cost_package %></td>
          <td><%= obj["unit_total"] %></td>
          <td><%= obj["sub_total"] %></td>
          <td>
            <%=
              link_to "/pos_sessions/#{@pos_session.id}/transaktions/delete/#{obj["item_id"]}?purchase=true",
                data: { turbo_method: :delete, turbo_confirm: "Estas seguro de eliminar?" } do
            %>
              <i class="fa fa-trash" color="black" aria-hidden="true"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td scope="row" colspan="6">
          <%=
            link_to "Borrar Todo", "/pos_sessions/#{@pos_session.id}/transaktions/delete_all?purchase=true",
              class: "text-decoration-none",
              data: {
                turbo_method: :delete,
                turbo_confirm: "Estas seguro de eliminar todo?"
              }
          %>
        </td>
        <th colspan="3">
          <span class="mx-2">
            Total:
          </span>
          <span class="h5 fw-bold" data-purchase-target="sumTotalItemTransactions">
            <%= total_mount.round(2) %>
          </span>
          <span class="h5 fw-bold">
            <%= @pos_session.type_of_currency %>
          </span>
        </th>
      </tr>
    </tbody>
  </table>
</div>

app/views/shared/tables/_table_items_added_sales.html.erb
<div class="table-responsive">
  <table class="table table-striped table-hover table-warehouse-items">
    <caption>Total registros: <%= item_transactions.count %></caption>
    <thead>
      <tr>
        <th scope="col">Código</th>
        <th scope="col" class="min-width-4">Descripción</th>
        <th scope="col">Unidades</th>
        <th scope="col">Cajas</th>
        <th scope="col">Precio</th>
        <th scope="col">Precio Caja</th>
        <th scope="col">Total Unidades</th>
        <th scope="col">Subtotal</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% total_mount = 0 %>
      <% item_transactions.each do |obj| %>
        <% item = Item.find(obj["item_id"]) %>
        <% total_mount += obj["sub_total"].to_f %>
        <tr>
          <td><%= item.code %></td>
          <td class="min-width-4" data-sales-target="itemDescription"><%= item.product.description %></td>
          <td><%= obj["qty_unit"] %></td>
          <td><%= obj["qty_package"] %></td>
          <td><%= item.sale_price_unit %></td>
          <td><%= item.sale_price_package %></td>
          <td><%= obj["unit_total"] %></td>
          <td><%= obj["sub_total"] %></td>
          <td>
            <%= link_to "/pos_sessions/#{@pos_session.id}/transaktions/delete/#{obj["item_id"]}?sales=true",
              data: { turbo_method: :delete, turbo_confirm: "Estas seguro de eliminar?" } do %>
              <i class="fa fa-trash" color="black" aria-hidden="true"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td scope="row" colspan="6">
          <%=
            link_to "Borrar Todo", "/pos_sessions/#{@pos_session.id}/transaktions/delete_all?sales=true",
              class: "text-decoration-none",
              data: {
                turbo_method: :delete,
                turbo_confirm: "Estas seguro de eliminar todo?"
              }
          %>
        </td>
        <th colspan="3">
          <span class="mx-2">
            Total:
          </span>
          <span class="h5 fw-bold" data-sales-target="sumTotalItemTransactions">
            <%= total_mount.round(2) %>
          </span>
          <span class="h5 fw-bold">
            <%= @pos_session.type_of_currency %>
          </span>
        </th>
      </tr>
    </tbody>
  </table>
</div>

app/views/shared/tables/_table_kardex.html.erb
<div class="table-responsive" data-controller="products">
  <table class="table table-striped table-hover table-warehouse-items">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col" class="min-width-1">Fecha</th>
        <th scope="col">Tipo</th>
        <th scope="col" class="min-width-2">Responsable</th>
        <th scope="col" class="min-width-2">Receptor</th>
        <th scope="col">Total Entrada</th>
        <th scope="col">Total Salida</th>
        <th scope="col">Saldo</th>
      </tr>
    </thead>
    <tbody>
      <% item_transaktions.each do |obj| %>
        <% transaktion = obj.transaktion %>
        <% path = pos_session_transaktion_path(transaktion.pos_session.id, transaktion.id) %>
        <tr
          class="cursor-pointer <%= transaktion.status == 'annulled' ? 'transaktion-annulled' : '' %>"
          id="<%= path %>" data-action="click->products#redirectShowProduct"
        >
          <th id="<%= path %>" scope="row"><%= transaktion.id %></th>
          <td id="<%= path %>" class="min-width-1">
            <%= transaktion.created_at.localtime.strftime("%Y-%m-%d %H:%M") %>
          </td>
          <td id="<%= path %>"><%= transaktion.type_transaktion_es %></td>
          <td id="<%= path %>" class="min-width-2">
            <%= transaktion.pos_session.user.full_name %>
          </td>
          <td id="<%= path %>" class="min-width-2">
            <% if transaktion.transfer? %>
              <%= transaktion.receiver_pos_session.user.full_name %>
            <% else %>
              <%=  transaktion.customer&.name %>
            <% end %>
          </td>
          <td id="<%= path %>">
            <% if (transaktion.purchase? || transaktion.purchase_credit?) && transaktion.active? %>
              <%= obj.qty %>
            <% elsif (transaktion.sale? || transaktion.market_rate? || transaktion.transfer?) && transaktion.annulled? %>
              <%= obj.qty %>
            <% else %>
              0
            <% end %>
          </td>
          <td id="<%= path %>">
            <% if (transaktion.sale? || transaktion.market_rate? || transaktion.transfer?) && transaktion.active? %>
              <%= obj.qty %>
            <% elsif (transaktion.purchase? || transaktion.purchase_credit?) && transaktion.annulled? %>
              <%= obj.qty %>
            <% else %>
              0
            <% end %>
          </td>
          <td id="<%= path %>"><%= obj.stock_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/tables/_table_orders_suggestions.html.erb
<div class="table-responsive">
  <table class="table table-striped table-hover table-warehouse-items">
    <thead>
      <tr>
        <th scope="col">Código</th>
        <th scope="col" class="min-width-4">Descripción</th>
        <th scope="col" class="min-width-3">Sucursal</th>
        <th scope="col" class="min-width-2">Proveedor</th>
        <th scope="col">Total stock</th>
        <th scope="col">Total ventas</th>
        <th scope="col">Total pedido</th>
        <th scope="col">Stock Min.</th>
        <th scope="col">Stock Max.</th>
      </tr>
    </thead>
    <tbody>
      <% items_suggestions.each do |obj| %>
        <tr>
          <td scope="row"><%= obj[:code] %></td>
          <td class="min-width-4"><%= obj[:description] %></td>
          <td class="min-width-2"><%= obj[:warehouse_name] %></td>
          <td><%= obj[:provider_name] %></td>
          <td><%= obj[:total_stock] %></td>
          <td><%= obj[:total_items_sold] %></td>
          <td><%= obj[:total_orders] %></td>
          <td><%= obj[:min_stock] %></td>
          <td><%= obj[:max_stock] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/tables/_table_payments.html.erb
<div class="table-responsive my-4">
  <table class="table table-striped table-hover table-warehouse-items">
    <caption>Cuentas por Pagar: <%= payments.count %></caption>
    <thead>
      <tr>
        <th>ID</th>
        <th scope="col" class="min-width-2">Fecha Compra</th>
        <th scope="col" class="min-width-2">Fecha Límite</th>
        <th scope="col" class="min-width-2">Total a Pagar</th>
        <th scope="col" class="min-width-3">Proveedor</th>
        <th scope="col" class="min-width-3">Realizado por</th>
      </tr>
    </thead>
    <tbody data-controller="pending">
      <% payments.each do |obj| %>
        <% redirect_id = pos_session_transaktion_path(obj.pos_session, obj.id) %>
        <tr
          id="<%= redirect_id %>" class="cursor-pointer"
          data-action="click->pending#redirectShowPending"
        >
          <td id="<%= redirect_id %>" scope="row"><%= obj.id %></td>
          <td id="<%= redirect_id %>" class="min-width-2">
            <%= obj.created_at.localtime.strftime("%d-%m-%Y %H:%M") %>
          </td>
          <th id="<%= redirect_id %>" class="min-width-2">
            <%= obj.date_of_payment.strftime("%d-%m-%Y") %>
          </th>
          <td id="<%= redirect_id %>" class="min-width-2">
            <%= obj.total %> <%= obj.pos_session.type_of_currency %>
          </td>
          <td id="<%= redirect_id %>" class="min-width-3">
            <%= obj.customer.name %>
          </td>
          <td id="<%= redirect_id %>" class="min-width-3">
            <%= obj.pos_session.user.short_name %>
            (<%= obj.pos_session.user.role.name_es || obj.pos_session.user.role.name %>)
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/tables/_table_pos_session.html.erb
<div class="table-responsive mt-5">
  <table class="table table-striped table-hover table-warehouse-items">
    <caption>Total Cajas: <%= pos_sessions.count %></caption>
    <thead>
      <tr>
        <th scope="col" class="text-center">ID</th>
        <th scope="col" class="min-width-3">Usuario</th>
        <th scope="col" class="min-width-6">Sucursal</th>
        <% unless current_user.sales? %>
          <th scope="col" class="min-width-1">Total Caja</th>
          <th scope="col" class="min-width-1">Total Ingresos</th>
          <th scope="col" class="min-width-1">Total Egresos</th>
        <% end %>
        <th scope="col">Estado</th>
      </tr>
    </thead>
    <tbody>
      <% pos_sessions.each do |obj| %>
        <% redirect_id = pos_session_path(obj) %>
        <tr
          id="<%= redirect_id %>" data-arching-target="urlShowPosSession"
          class="cursor-pointer" data-action="click->arching#redirectShowPosSession"
        >
          <th id="<%= redirect_id %>" scope="row"><%= obj.id %></th>
          <td id="<%= redirect_id %>" class="min-width-3">
            <%= obj.user.name %> <%= obj.user.last_name %>
            (<%= obj.user.role.name_es || obj.user.role.name %>)
          </td>
          <td id="<%= redirect_id %>" class="min-width-6">
              <%= "#{obj.warehouse.name} " %>
              <%= obj.warehouse.warehouse_detail ? obj.warehouse.warehouse_detail.address : "" %>
          </td>
          <% unless current_user.sales? %>
            <td id="<%= redirect_id %>" class="min-width-1">
              <%= obj.total_session ? obj.total_session : 0.0 %> <%= obj.type_of_currency %>
            </td>
            <td id="<%= redirect_id %>" class="min-width-1">
              <%= obj.total_income ? obj.total_income : 0.0 %> <%= obj.type_of_currency %>
            </td>
            <td id="<%= redirect_id %>" class="min-width-1">
              <%= obj.total_expenses ? obj.total_expenses : 0.0 %> <%= obj.type_of_currency %>
            </td>
          <% end %>
          <td id="<%= redirect_id %>"><%= obj.status_es %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/tables/_table_product.html.erb
<div class="table-responsive">
  <table class="table table-striped table-hover table-warehouse-items">
    <caption>Total productos: <%= products.count %></caption>
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col" class="min-width-2">Nombre</th>
        <th scope="col" class="min-width-2">Nombre Genérico</th>
        <th scope="col" class="min-width-4">Descripción</th>
        <th scope="col">Presentación</th>
        <th scope="col" class="min-width-2">Proveedor</th>
        <th scope="col">Código</th>
        <th scope="col" class="min-width-2">Unidad</th>
        <th scope="col">Paq./Caja</th>
        <th scope="col" class="min-width-2">Marca</th>
        <th scope="col">Categoria</th>
        <th scope="col">Estado</th>
      </tr>
    </thead>
    <tbody>
      <% products.each do |obj| %>
        <% redirect_id = product_path(obj) %>
        <tr
          class="cursor-pointer" id="<%= redirect_id %>"
          data-action="click->products#redirectShowProduct"
        >
          <th id="<%= redirect_id %>" scope="row"><%= obj.id %></th>
          <td id="<%= redirect_id %>" class="min-width-2"><%= obj.name %></td>
          <td id="<%= redirect_id %>" class="min-width-2"><%= obj.generic_name %></td>
          <td id="<%= redirect_id %>" class="min-width-4"><%= obj.description %></td>
          <td id="<%= redirect_id %>"><%= obj.presentation %></td>
          <td id="<%= redirect_id %>" class="min-width-2">
            <%= obj&.customer&.name || obj&.customer&.company_name || obj&.customer&.social_reason %>
          </td>
          <td id="<%= redirect_id %>"><%= obj.code %></td>
          <td id="<%= redirect_id %>" class="min-width-2"><%= obj.unit %></td>
          <td id="<%= redirect_id %>"><%= obj.package %></td>
          <td id="<%= redirect_id %>" class="min-width-2"><%= obj.trademark %></td>
          <td id="<%= redirect_id %>"><%= obj.category %></td>
          <td id="<%= redirect_id %>"><%= obj.status_es %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/tables/_table_transaktion.html.erb
<div class="table-responsive">
  <table class="table table-striped table-hover table-warehouse-items">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <% unless defined?(sales) %>
          <th scope="col" class="min-width-1">Tipo</th>
        <% end %>
        <th scope="col"><%= defined?(sales) ?  'Cliente' : 'Cliente/Proveedor' %></th>
        <% unless current_user.sales? %>
          <th scope="col" class="min-width-1">Total</th>
        <% end %>
        <th scope="col">Hora</th>
        <th scope="col">Estado</th>
      </tr>
    </thead>
    <tbody>
      <% transaktions.each do |obj| %>
        <% redirect_id = pos_session_transaktion_path(@pos_session, obj) %>
        <tr
          id="<%= redirect_id %>" class="cursor-pointer"
          data-action="click->transaktions#redirectShowTransaktion"
        >
          <th id="<%= redirect_id %>" scope="row"><%= obj.id %></th>
          <% unless defined?(sales) %>
            <td id="<%= redirect_id %>" class="min-width-1"><%= obj.type_transaktion_es %></td>
          <% end %>
          <td id="<%= redirect_id %>" class="min-width-3">
            <%= obj.customer&.name %>
          </td>
          <% unless current_user.sales? %>
            <td id="<%= redirect_id %>" class="min-width-1"><%= obj.total %> <%= obj.pos_session.type_of_currency %></td>
          <% end %>
          <td id="<%= redirect_id %>"><%= obj.created_at.localtime.strftime("%H:%M:%S") %></td>
          <td id="<%= redirect_id %>"><%= obj.status_es %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>