config/routes.rb
Rails.application.routes.draw do
  get "download_pdf/:warehouse_id", to: "items#download_pdf", as: "download_pdf"
  get "preview_pdf/:warehouse_id", to: "items#preview_pdf", as: "preview_pdf"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  resources :users_admin, controller: 'users' do
    collection do
      post '/search_users', to: 'users#search_users', as: :search_users
    end
    resources :access_alloweds, only: %i[create new destroy] do
      collection do
        post '/search_warehouse', to: 'access_alloweds#search_warehouse', as: :search_warehouse
      end
    end
  end
  resources :pos_sessions do
    get '/transaktions/:id/annullated', to: 'transaktions#annullated', as: 'transaktion_annullated'
    get '/transaktions/:id/paying', to: 'transaktions#paying', as: 'transaktion_paying'
    resources :transaktions, only: %i[index create edit update destroy show] do
      collection do
        delete '/delete/:id', to: 'search_transaktions#delete_session', as: :delete
        delete '/delete_all', to: 'search_transaktions#delete_all_session', as: :delete_all
        post '/search', to: 'search_transaktions#search_product_purchase', as: :search
        post '/search_transaktions', to: 'search_transaktions#search_transaktions', as: :search_transaktions
        post '/search_sale', to: 'search_transaktions#search_product_sale', as: :search_sale
        post '/search_market', to: 'search_transaktions#search_market_rates', as: :search_market
        post '/search_provider', to: 'search_transaktions#search_provider', as: :search_provider
        post '/search_warehouse', to: 'search_transaktions#search_warehouse', as: :search_warehouse
        post '/create_sale', to: 'search_transaktions#create_sales_with_customer', as: :create_sale
        post '/create_transfer', to: 'search_transaktions#create_item_transfer', as: :create_transfer
        post '/item_transactions', to: 'search_transaktions#item_transactions_session', as: :item_transactions
      end
    end

    collection do
      post '/search_pos_sessions', to: 'pos_sessions#search_pos_sessions', as: :search_pos_sessions
    end

    get '/sales', to: 'transaktions#sales'
    get '/purchases', to: 'transaktions#purchases'
    get '/market_rates', to: 'transaktions#market_rates'
    get '/item_transfer', to: 'transaktions#item_transfer'
    get '/modal_create_product', to: 'search_transaktions#modal_create_product'
    get '/modal_confirm_market_rates', to: 'search_transaktions#modal_confirm_market_rates'
    get '/modal_confirm_transfer', to: 'search_transaktions#modal_confirm_transfer'
  end

  get '/payment_center', to: 'transaktions#payment_center'

  resources :providers do
    collection do
      get '/modal_new', to: 'providers#modal_new'
      post '/searches', to: 'providers#searches'
      post '/search', to: 'providers#search'
    end
  end

  resources :buyers do
    collection do
      post '/searches', to: 'buyers#searches'
      post '/search', to: 'buyers#search'
    end
  end

  resources :orders, only: :index

  resources :products do
    collection do
      post '/search_products', to: 'products#search_products', as: :search_products
      post '/search_providers', to: 'products#search_providers', as: :search_providers
    end
  end
  resources :accounts, only: %i[create show edit update destroy]
  resources :warehouses do
    collection do
      post '/search_warehouses', to: 'warehouses#search_warehouses', as: :search_warehouses
    end
    resources :warehouse_details, only: %i[create update]
    resources :items do
      collection do
        post '/search_product', to: 'items#search_product', as: :search_product
        post '/search_items', to: 'items#search_items', as: :search_items
      end
    end
  end
end

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
# Defines the root path route ("/")

app/models/pos_session.rb
class PosSession < ApplicationRecord
  belongs_to :warehouse

  has_many :transaktions
  has_many :archings

  validates :petty_cash, :user_id, numericality: true, presence: true
  validates :type_of_currency, presence: true

  enum status: %i[active deleted closed validating]

  def user
    User.find(user_id)
  end

  def session_responsible
    "#{user.short_name} (Caja: #{id})"
  end

  STATUS_ES = {
    'active' => 'Activo', 'deleted' => 'Eliminado', 'closed' => 'Cerrado',
    'validating' => 'Validando'
  }.freeze

  def status_es
    STATUS_ES[status]
  end
end

# == Schema Information
#
# Table name: pos_sessions
#
#  id                    :bigint           not null, primary key
#  initial_balance       :float(24)        default(0.0)
#  missing_money         :float(24)
#  observation           :string(255)
#  petty_cash            :float(24)
#  remaining_money       :float(24)
#  status                :integer          default("active")
#  total_balance         :float(24)
#  total_expenses        :float(24)
#  total_income          :float(24)
#  total_payment_methods :json
#  total_session         :float(24)
#  type_of_currency      :string(255)
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  user_id               :integer          not null
#  warehouse_id          :bigint           not null
#
# Indexes
#
#  index_pos_sessions_on_warehouse_id  (warehouse_id)
#
# Foreign Keys
#
#  fk_rails_...  (warehouse_id => warehouses.id)
#

app/controllers/pos_sessions_controller.rb
class PosSessionsController < ApplicationController
  before_action :set_pos_session, only: %i[show edit update destroy]
  before_action :set_breadcrumbs_pos_session, only: %i[index new edit show]
  before_action :skip_authorization, only: :search_pos_sessions

  def index
    @filter_pos_sessions = set_filter_pos_sessions
    if params[:type_filter].present?
      @pos_sessions = policy_scope(PosSession).where(
        status: params[:type_filter]
      ).page(params[:page]).per(15).order(id: :desc)
    else
      @pos_sessions = policy_scope(PosSession).page(params[:page]).per(15).order(id: :desc)
    end
    authorize @pos_sessions
    @pos_session_active = PosSession.find_by(user_id: current_user.id, status: 'active')
    @pos_session_pending = PosSession.find_by(user_id: current_user.id, status: 'validating')
    redirect_to pos_session_path(@pos_session_active) if @pos_session_active
    redirect_to pos_session_path(@pos_session_pending) if @pos_session_pending
  end

  def search_pos_sessions
    @pos_sessions = search_pos_sessions_filter

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update(
          'search_results_pos_sessions_index',
          partial: 'shared/tables/table_pos_session',
          locals: { pos_sessions: @pos_sessions }
        )
      end
    end
  end

  def new
    @pos_session = PosSession.new
    @warehouse_ids = set_access_allowed_warehouse_ids
    authorize @pos_session
  end

  def create
    @pos_session = PosSession.new(pos_session_params)
    @warehouse_ids = set_access_allowed_warehouse_ids
    @pos_session.user_id = current_user.id
    authorize @pos_session

    if @pos_session.valid?
      @pos_session.save
      redirect_to pos_session_path(@pos_session), notice: 'Se Abrio una nueva Caja con exito!'
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @sale_transaktions = @pos_session.transaktions.where(
      type_transaktion: 'Sales'
    ).page(params[:page]).per(20)

    @income_annullated = Transaktion.where(
      type_transaktion: ['Sales', 'Market rates'], status: 'annulled',
      receiver_pos_session_id: @pos_session.id
    ).map(&:total).sum

    @expenses_annullated = Transaktion.where(
      type_transaktion: ['Purchases', 'Purchases Credit'], status: 'annulled',
      receiver_pos_session_id: @pos_session.id
    ).map(&:total).sum

    if @pos_session.total_payment_methods
      @total_payment_methods = JSON.parse(@pos_session.total_payment_methods)
    end
  end

  def edit
    @arching_ticketings = set_arching_ticketing
  end

  def update
    update_pos_session(@pos_session) unless @pos_session.status == 'validating'
    closed_pos_session_forced(@pos_session)
    arching_closed_message = 'Arqueo finalizado, Se cerro la Caja correctamente.' if @pos_session.closed?

    if @pos_session.update(pos_session_params)
      redirect_to pos_session_path(@pos_session), notice: arching_closed_message
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    if @pos_session.update(status: 1)
      redirect_to pos_sessions_path
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  private

  def pos_session_params
    params.require(:pos_session).permit(
      :id, :warehouse_id, :petty_cash, :type_of_currency, :status, :observation,
      :total_balance, :initial_balance, :missing_money, :remaining_money,
      :total_session, :user_id, :total_income, :total_expenses
    )
  end

  def set_pos_session
    @pos_session = PosSession.find(params[:id])
    authorize @pos_session
  end

  def update_pos_session(pos_session)
    purchase_credit_confirms = Transaktion.where(
      type_transaktion: 'Purchases Credit', status: 'active',
      receiver_pos_session_id: pos_session.id
    )

    total_income = 0
    total_expenses = 0

    if purchase_credit_confirms.any?
      purchase_credit_confirms.each do |obj|
        total_expenses += obj.total
      end
    end

    pos_session.transaktions.each do |obj|
      if obj.type_transaktion == 'Purchases' && obj.status == 'active'
        total_expenses += obj.total
      elsif obj.type_transaktion == 'Sales' && obj.status == 'active'
        total_income += obj.total
      elsif obj.type_transaktion == 'Market rates' && obj.status == 'active'
        total_income += obj.total
      end
    end

    total_session = (pos_session.petty_cash + total_income - total_expenses).round(2)

    operation_result = (
      pos_session_params[:total_balance].to_f.round(2) - total_session.abs
    ).round(2)

    missing_money = operation_result <= 0 ? operation_result.abs : 0
    remaining_money = operation_result >= 0 ? operation_result : 0

    pos_session.total_balance = pos_session_params[:total_balance]
    pos_session.missing_money = missing_money
    pos_session.remaining_money = remaining_money
    pos_session.total_income = total_income.round(2)
    pos_session.total_expenses = total_expenses.round(2)
    pos_session.total_session = total_session.negative? ? 0 : total_session
    pos_session.status = 'validating' if pos_session.status == 'active'
    pos_session.status = 'closed' if pos_session.total_balance >= pos_session.total_session
    set_total_payment_methods(@pos_session)
  end

  def set_total_payment_methods(pos_session)
    total_income_qr = set_total_income_transaktion(pos_session, 'Pago QR')
    total_expenses_qr = set_total_expenses_transaktion(pos_session, 'Pago QR', 'Purchases')
    total_expenses_qr_credit = set_total_expenses_transaktion(pos_session, 'Pago QR', 'Purchases Credit')

    total_income_ca = set_total_income_transaktion(pos_session, 'Tarjeta')
    total_expenses_ca = set_total_expenses_transaktion(pos_session, 'Tarjeta', 'Purchases')
    total_expenses_ca_credit = set_total_expenses_transaktion(pos_session, 'Tarjeta', 'Purchases Credit')

    total_income_tr = set_total_income_transaktion(pos_session, 'Transferencia')
    total_expenses_tr = set_total_expenses_transaktion(pos_session, 'Transferencia', 'Purchases')
    total_expenses_tr_credit = set_total_expenses_transaktion(pos_session, 'Transferencia', 'Purchases Credit')

    total_income_ef = set_total_income_transaktion(pos_session, 'Efectivo')
    total_expenses_ef = set_total_expenses_transaktion(pos_session, 'Efectivo', 'Purchases')
    total_expenses_ef_credit = set_total_expenses_transaktion(pos_session, 'Efectivo', 'Purchases Credit')

    total_payment_methods_json = {
      total_arching_money: JSON.parse(params[:total_arching_money]),
      income: {
        qr: { total: total_income_qr.round(2) },
        cash: { total: total_income_ef.round(2) },
        card: { total: total_income_ca.round(2) },
        transfer: { total: total_income_tr.round(2) }
      },
      expenses: {
        qr: { total: (total_expenses_qr + total_expenses_qr_credit).round(2) },
        cash: { total: (total_expenses_ef + total_expenses_ef_credit).round(2) },
        card: { total: (total_expenses_ca + total_expenses_ca_credit).round(2) },
        transfer: { total: (total_expenses_tr + total_expenses_tr_credit).round(2) }
      }
    }.to_json

    pos_session.total_payment_methods = total_payment_methods_json
  end

  def closed_pos_session_forced(pos_session)
    if pos_session.status == 'validating' && params[:arching_forced] == 'true'
      pos_session.update(status: 'closed')
    end
  end

  def set_access_allowed_warehouse_ids
    access_alloweds = []
    access_alloweds_user = AccessAllowed.where(user_id: current_user.id).order(warehouse_id: :asc)
    access_alloweds_user.each do |access|
      access_alloweds << [
        "#{access.warehouse.name} (#{access.warehouse&.warehouse_detail&.branch_code})",
        access.warehouse_id
      ]
    end
    access_alloweds
  end

  def set_arching_ticketing
    [
      { action_target: 'value200',  value_target: 'doscientos', img: '200bs.jpg' },
      { action_target: 'value100',  value_target: 'cien', img: '100bs.jpg' },
      { action_target: 'value50',  value_target: 'cincuenta', img: '50bs.jpg' },
      { action_target: 'value20',  value_target: 'veinte', img: '20bs.jpg' },
      { action_target: 'value10',  value_target: 'diez', img: '10bs.jpg' },
      { action_target: 'value5',  value_target: 'cinco', img: '5bs.png' },
      { action_target: 'value2',  value_target: 'dos', img: '2bs.jpg' },
      { action_target: 'value1',  value_target: 'uno', img: '1bs.jpg' },
      { action_target: 'value050',  value_target: 'cerocincuenta', img: '50ctvs.jpeg' },
      { action_target: 'value020',  value_target: 'ceroveinte', img: '20ctvs.jpg' },
      { action_target: 'value010',  value_target: 'cerodiez', img: '10ctvs.jpg' }
    ]
  end

  def set_breadcrumbs_pos_session
    add_breadcrumb 'Cajas', :pos_sessions_path
    add_breadcrumb @pos_session.warehouse.name, :pos_session_path if @pos_session
    add_breadcrumb 'Abrir Caja', :new_pos_session_path if action_name == 'new'
    add_breadcrumb 'Billetaje', :edit_pos_session_path if action_name == 'edit'
  end

  def search_pos_sessions_filter
    PosSession.joins('INNER JOIN users ON pos_sessions.user_id = users.id')
              .joins('INNER JOIN warehouses ON pos_sessions.warehouse_id = warehouses.id')
              .joins('INNER JOIN roles ON users.role_id = roles.id')
              .where(
                'LOWER(roles.name) LIKE :query OR LOWER(users.name) LIKE :query OR LOWER(users.last_name) LIKE :query OR LOWER(warehouses.name) LIKE :query OR LOWER(users.email) LIKE :query',
                query: "%#{params[:search_pos_sessions].downcase}%"
              ).where(warehouse_id: current_account.warehouses.map(&:id)).limit(30)
  end

  def set_filter_pos_sessions
    [
      ['Caja Activa', 'active'], ['Caja Cerrada', 'closed'], ['Caja Arqueando', 'validating']
    ]
  end

  def set_total_expenses_transaktion(session, payment_method, type_transaktion)
    if type_transaktion == 'Purchases Credit'

app/helpers/pos_sessions_helper.rb
module PosSessionsHelper
end

app/views/pos_sessions/_render_show_active.html.erb
<section class="row justify-content-center app-papper" data-controller="arching">
  <div class="col-12 col-md-6 pos-session-info">
    <h5><span>Usuario: </span>
      <%= @pos_session.user.name %> <%= @pos_session.user.last_name %>
      (<%= @pos_session.user.role.name_es || @pos_session.user.role.name %>)
    </h5>
    <h5><span>Sucursal:</span> <%= @pos_session.warehouse.name %></h5>
    <h5>
      <span>Caja Chica: </span>
      <%= @pos_session.petty_cash %>
      <%= @pos_session.type_of_currency %>
    </h5>
    <h5><span>Observación:</span> <%= @pos_session.observation %></h5>
    <h5><span>Estado de la Caja:</span> <%= @pos_session.status %></h5>
    <h5>
      <span>Inicio de Caja: </span>
      <%= @pos_session.created_at.localtime.strftime("%Y-%m-%d %H:%M") %>
    </h5>
    <% if @pos_session.created_at == @pos_session.updated_at %>
        <h5>
          <span>Cierre de Caja: </span>
          Hasta el momento
        </h5>
    <% else %>
        <h5>
          <span>Cierre de Caja: </span>
          <%= @pos_session.updated_at.localtime.strftime("%Y-%m-%d %H:%M") %>
        </h5>
    <% end %>
  </div>
  <div class="col-12 col-md-6 pos-session-info">
    <% if current_user.owner_or_admin? %>
      <h5>
        <span>Total billetaje: </span>
        <%= @pos_session.total_balance ?
            "#{@pos_session.total_balance} #{@pos_session.type_of_currency}": "" %>
      </h5>
      <h5>
        <span>Total Ingresos: </span>
        <%= @pos_session.total_income ?
            "#{@pos_session.total_income} #{@pos_session.type_of_currency}" : "" %>
      </h5>
      <h5>
        <span>Total Egresos: </span>
        <%= @pos_session.total_expenses ?
            "#{@pos_session.total_expenses} #{@pos_session.type_of_currency}" : "" %>
      </h5>
      <h5>
        <span>Dinero Sobrante: </span>
        <%= @pos_session.remaining_money ?
            "#{@pos_session.remaining_money} #{@pos_session.type_of_currency}" : "" %>
      </h5>
      <h5>
        <span>Total en Caja: </span>
        <%= @pos_session.total_session ?
            "#{@pos_session.total_session} #{@pos_session.type_of_currency}" : "" %>
      </h5>
      <h5>
        <span>Dinero Faltante: </span>
        <%= @pos_session.missing_money ?
            "#{@pos_session.missing_money} #{@pos_session.type_of_currency}" : "" %>
      </h5>
      <h5>
        <span>Egresos Anulados: </span>
        <%= "#{@expenses_annullated} #{@pos_session.type_of_currency}" %>
      </h5>
      <h5>
        <span>Ingresos Anulados: </span>
        <%= "#{@income_annullated} #{@pos_session.type_of_currency}" %>
      </h5>
    <% end %>
  </div>
  <div class="col-12 col-md-6 pos-session-info info-arching-close-selector d-none">
    <% if @total_payment_methods && current_user.owner_or_admin? %>
      <% @total_payment_methods["total_arching_money"].deep_symbolize_keys.each do |key, value| %>
        <h5>
          <span><%= value[:title] %>: </span>
          <span class="mx-2 h6">
            Cantidad: <%= value[:cash_qty] %>,
          </span>
          <span class="h6">
            Total: <%= value[:total] %>
          </span>
        </h5>
      <% end %>
    <% end %>
  </div>
  <div class="col-12 col-md-6 pos-session-info info-arching-close-selector d-none">
    <% if @total_payment_methods && current_user.owner_or_admin? %>
      <h5>
        <span>Total Ingresos Efectivo: </span>
        <%= @total_payment_methods["income"]["cash"]["total"] %>
        <%= @pos_session.type_of_currency %>
      </h5>
      <h5>
        <span>Total Egresos Efectivo: </span>
        <%= @total_payment_methods["expenses"]["cash"]["total"] %>
        <%= @pos_session.type_of_currency %>
      </h5>
      <h5>
        <span>Total Ingresos QR: </span>
        <%= @total_payment_methods["income"]["qr"]["total"] %>
        <%= @pos_session.type_of_currency %>
      </h5>
      <h5>
        <span>Total Egresos QR: </span>
        <%= @total_payment_methods["expenses"]["qr"]["total"] %>
        <%= @pos_session.type_of_currency %>
      </h5>
      <h5>
        <span>Total Ingresos Tarjeta: </span>
        <%= @total_payment_methods["income"]["card"]["total"] %>
        <%= @pos_session.type_of_currency %>
      </h5>
      <h5>
        <span>Total Egresos Tarjeta: </span>
        <%= @total_payment_methods["expenses"]["card"]["total"] %>
        <%= @pos_session.type_of_currency %>
      </h5>
      <h5>
        <span>Total Ingresos Transferencia: </span>
        <%= @total_payment_methods["income"]["transfer"]["total"] %>
        <%= @pos_session.type_of_currency %>
      </h5>
      <h5>
        <span>Total Egresos Transferencia: </span>
        <%= @total_payment_methods["expenses"]["transfer"]["total"] %>
        <%= @pos_session.type_of_currency %>
      </h5>
    <% end %>
  </div>
  <div class="col-12">
    <% if @pos_session.status == 'closed' %>
      <button
        type="button"
        data-action="click->arching#toggleShowArchingDetails"
        class="btn btn-outline-primary mt-3"
      >
        Detalles del arqueo
      </button>
    <% end %>
    <% if @pos_session.status == 'active' %>
      <% if policy(@pos_session).edit? %>
        <%= link_to "Realizar Arqueo", edit_pos_session_path(@pos_session),
          class: "btn btn-outline-primary mx-1 mt-3" %>
      <% end %>
      <% if policy(@pos_session).sales? %>
        <%= link_to "Vender", pos_session_sales_path(@pos_session),
          class: "btn btn-primary mx-1 mt-3" %>
      <% end %>
      <% if policy(@pos_session).purchases? %>
        <%= link_to "Comprar", pos_session_purchases_path(@pos_session),
          class: "btn btn-outline-primary mx-1 mt-3" %>
      <% end %>
      <% if policy(@pos_session).market_rates? %>
        <%= link_to "Cotizar", pos_session_market_rates_path(@pos_session),
            class: "btn btn-outline-primary mx-1 mt-3" %>
      <% end %>
      <% if policy(@pos_session).item_transfer? %>
        <%= link_to "Traspaso", pos_session_item_transfer_path(@pos_session),
            class: "btn btn-outline-primary mx-1 mt-3" %>
      <% end %>
      <% if current_user.owner_or_admin_or_sales? %>
        <%=
          link_to "Confirmar Traspaso", pos_session_modal_confirm_transfer_path(@pos_session),
            class: "btn btn-outline-primary mx-1 mt-3",
            data: { turbo_frame: "modal_confirm_transfer" }
        %>
      <% end %>
    <% end %>
    <% if policy(Transaktion).index? %>
      <%= link_to "Movimientos", pos_session_transaktions_path(@pos_session),
        class: "btn btn-outline-primary mx-1 mt-3" %>
    <% end %>
  </div>
</section>
<section class="row app-papper mt-4">
  <div class="col-12" data-controller="transaktions">
    <h4 class="text-center mb-5"><b>Ventas</b></p>
    <%= render partial: 'shared/tables/table_transaktion',
        locals: { transaktions: @sale_transaktions, sales: true } %>
    <%= render partial: 'shared/pagination', locals: { records_pagination: @sale_transaktions } %>
  </div>
</section>

app/views/pos_sessions/_render_show_validating.html.erb
<section class="app-papper row justify-content-center">
  <div class="col-12 col-md-8 col-lg-7 text-center">
    <% if @pos_session.missing_money > 0 %>
      <div class="mt-5">
        <h2 class="mt-3  text-danger">
          Dinero Faltante:
          <%= @pos_session.type_of_currency %>
          <%= @pos_session.missing_money %>
        </h2>
        <h5>
          Finaliza el cierre dejando un comentario para una revisión futura.
        </h5>
        <div class="my-4" data-controller="arching">
          <%= bootstrap_form_for(@pos_session,
              data: { arching_target: "formConfirmArchingValidating" }) do |f| %>
            <div class="row justify-content-center text-center">
              <input
                type="hidden" value="false" name="arching_forced"
                data-arching-target="archingForcedValue"
              >
              <div class="col-12">
                <%= f.text_area :observation, rows: 3, label: "Observación" %>
              </div>
              <div class="col-6 col-md-4">
                <button
                  type="button" class="btn btn-primary"
                  data-action="click->arching#setForceClosedSession"
                >
                  Cerrar Caja
                </button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/pos_sessions/index.html.erb
<section class="app-papper row justify-content-between mb-3" data-controller="arching">
  <% if policy(PosSession).purchases? %>
    <div class="col-6 col-md-5">
      <%= form_with url: search_pos_sessions_pos_sessions_path,
          method: :post, class: "purchase-search-products-form",
          data: { arching_target: "formSearchPosSessions" } do |form|
      %>
        <%= form.label "Buscar Caja" %>
        <%=
          form.search_field :search_pos_sessions, id: "search-input",
            class: "form-control purchase-search-input",
            data: {
              action: "input->arching#searchPosSessions",
              arching_target: "inputSearchPosSessions"
            }
        %>
      <% end %>
    </div>
  <% end %>
  <div class="col-6 col-md-4 col-lg-3">
    <%= form_with url: pos_sessions_path,
        method: :get, class: "purchase-search-products-form",
        data: { arching_target: "formSearchPosSessionsFilter" } do |form|
    %>
      <%= form.label "Filtrar por:" %>
      <%=
        form.select :type_filter,  options_for_select(@filter_pos_sessions, params[:type_filter]),
          { include_blank: 'Seleccionar' },
          class: "form-control purchase-search-input",
          data: { action: "change->arching#sendRequestPosSessionFilter" }
      %>
    <% end %>
  </div>
  <div class="col-4 col-md-4 col-lg-3 col-xl-2">
    <%= link_to "Abrir Caja", new_pos_session_path, class: "btn btn-primary mt-4" %>
  </div>
  <div class="col-12" id="search_results_pos_sessions_index">
    <%= render partial: 'shared/tables/table_pos_session', locals: { pos_sessions: @pos_sessions} %>
    <%= render partial: 'shared/pagination', locals: { records_pagination: @pos_sessions } %>
  </div>
</section>

app/views/pos_sessions/new.html.erb
<section class="user-form-container app-form-papper">
  <div class="row">
    <h5 class="mt-3 mb-5 text-center">Apertura de Caja</h5>
    <div class="col-12">
      <%= bootstrap_form_for(@pos_session) do |f| %>
        <div class="row" >
          <%= f.hidden_field :initial_balance, value: 0 %>
          <div class="col-12 col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-6">
            <%= f.number_field :petty_cash, label: t('forms.models.pos_session.labels.petty_cash'), append: 'Bs.', autofocus: true %>
          </div>
          <div class="col-12 col-md-6 col-lg-6 col-xl-6">
            <%= f.select :warehouse_id, options_for_select(@warehouse_ids),
                  required: true, prompt: 'Elegir' , option_class: "select",
                  label: t('forms.models.pos_session.labels.warehouse_select') %>
          </div>
          <div class="col-12 col-md-6 col-lg-6 col-xl-6">
            <%= f.select :type_of_currency,
                  options_for_select([['Bolivianos', 'Bs'], ['Dolares USD', '$us']]), required: true,
                 option_class: "select", label: t('forms.models.pos_session.labels.type_of_currency') %>
          </div>
          <div class="col-12 col-md-6 col-lg-6 col-xl-6">
            <%= f.text_field :observation, label: t('forms.models.pos_session.labels.observation') %>
          </div>
        <div class="row">
          <div class="col-4 col-md-4 col-lg-4 col-xl-4 mb-4 mt-1">
            <%= f.submit "Abrir Caja", class: "btn btn-primary" %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</section>

app/views/pos_sessions/show.html.erb
<section class="pos-session-show-container">
  <div class="pos-session-info-container">
    <% if @pos_session.status == 'validating' %>
      <%= render 'render_show_validating', locals: { pos_session: @pos_session } %>
    <% else %>
      <%= render 'render_show_active', locals: { pos_session: @pos_session } %>
    <% end %>
  </div>
</section>